### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Gabs00**
Added Express Server, and Server logging

### CODE REVIEW

**Comment by mistermark** [comment]
@Gabs00 forgot to include Express in the package.json. Once the server is running it also spits out error logs it can't find Bootstrap stuff.

```
[2015-08-16 10:59:04.500] [WARN] [default] - ::1 - - "GET / HTTP/1.1" 304 - "" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:41.0) Gecko/20100101 Firefox/41.0"
[2015-08-16 10:59:04.511] [WARN] [default] - ::1 - - "GET /css/normalize.css HTTP/1.1" 304 - "http://localhost:1337/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:41.0) Gecko/20100101 Firefox/41.0"
[2015-08-16 10:59:04.512] [WARN] [default] - ::1 - - "GET /css/main.css HTTP/1.1" 304 - "http://localhost:1337/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:41.0) Gecko/20100101 Firefox/41.0"
[2015-08-16 10:59:04.513] [ERROR] [default] - ::1 - - "GET /lib/bootstrap/dist/css/bootstrap.css HTTP/1.1" 404 140 "http://localhost:1337/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:41.0) Gecko/20100101 Firefox/41.0"
[2015-08-16 10:59:04.517] [WARN] [default] - ::1 - - "GET /js/vendor/modernizr-2.8.3.min.js HTTP/1.1" 304 - "http://localhost:1337/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:41.0) Gecko/20100101 Firefox/41.0"
Error: ENOENT, stat '/Users/mark/Code/NPM/gentleman/client/lib/bootstrap/dist/css/bootstrap.css'
    at Error (native)
[2015-08-16 10:59:04.519] [WARN] [default] - ::1 - - "GET /js/main.js HTTP/1.1" 304 - "http://localhost:1337/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:41.0) Gecko/20100101 Firefox/41.0"
[2015-08-16 10:59:04.521] [ERROR] [default] - ::1 - - "GET /lib/jquery/dist/jquery.js HTTP/1.1" 404 129 "http://localhost:1337/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:41.0) Gecko/20100101 Firefox/41.0"
[2015-08-16 10:59:04.522] [ERROR] [default] - ::1 - - "GET /lib/bootstrap/dist/js/bootstrap.js HTTP/1.1" 404 138 "http://localhost:1337/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:41.0) Gecko/20100101 Firefox/41.0"
[2015-08-16 10:59:04.523] [WARN] [default] - ::1 - - "GET /js/plugins.js HTTP/1.1" 304 - "http://localhost:1337/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:41.0) Gecko/20100101 Firefox/41.0"
Error: ENOENT, stat '/Users/mark/Code/NPM/gentleman/client/lib/jquery/dist/jquery.js'
    at Error (native)
Error: ENOENT, stat '/Users/mark/Code/NPM/gentleman/client/lib/bootstrap/dist/js/bootstrap.js'
    at Error (native)
[2015-08-16 10:59:04.561] [ERROR] [default] - ::1 - - "GET /lib/jquery/dist/jquery.js HTTP/1.1" 404 129 "http://localhost:1337/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:41.0) Gecko/20100101 Firefox/41.0"
Error: ENOENT, stat '/Users/mark/Code/NPM/gentleman/client/lib/jquery/dist/jquery.js'
    at Error (native)
[2015-08-16 10:59:04.566] [ERROR] [default] - ::1 - - "GET /lib/bootstrap/dist/js/bootstrap.js HTTP/1.1" 404 138 "http://localhost:1337/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:41.0) Gecko/20100101 Firefox/41.0"
Error: ENOENT, stat '/Users/mark/Code/NPM/gentleman/client/lib/bootstrap/dist/js/bootstrap.js'
    at Error (native)
```

**Comment by mistermark** [comment]
Also, do we want to manage these front-end dependencies using bower? Would love to hear your opinion about this.

**Comment by Gabs00** [comment]
There should be a bower.json bower install should get the deps

**Comment by Gabs00** [comment]
I'll update the package.json and also add bower install to it

**Comment by Gabs00** [comment]
@mistermark  Try now

**Comment by Gabs00** [comment]
Going to close this and seperate gentleman cli and gentleman-webapp

**Pull request closed without merging**
